apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-release
  namespace: flux-system
spec:
  releaseName: cert-manager
  timeout: 1m0s
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      version: '1.15.3'
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  targetNamespace: cert-manager
  interval: 1m0s
  values:
    crds:
      enabled: true
