apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tyk-app-claim
  namespace: tyk-oss
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""  # Adjust according to your GKE cluster's storage class
  selector:
    matchLabels:
      volume: filestore-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tyk-policies-claim
  namespace: tyk-oss
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""  # Adjust according to your GKE cluster's storage class
  selector:
    matchLabels:
      volume: filestore-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tyk-middleware-claim
  namespace: tyk-oss
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""  # Adjust according to your GKE cluster's storage class
  selector:
    matchLabels:
      volume: filestore-pv
