apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestore-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: filestore-rwx
  nfs:
    path: /gkerwx  # This should be the path of your file share
    server: 10.149.212.26	  # The IP address of your Filestore instance
