apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tyk-app-claim
  namespace: tyk-oss
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: filestore-rwx  # Adjust according to your GKE cluster's storage class
  volumeName: filestore-app

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tyk-policies-claim
  namespace: tyk-oss
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: filestore-rwx  # Adjust according to your GKE cluster's storage class
  volumeName: filestore-policies
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tyk-middleware-claim
  namespace: tyk-oss
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: filestore-rwx  # Adjust according to your GKE cluster's storage class
  volumeName: filestore-middleware
