---

apiVersion: v1
kind: Namespace
metadata:
  name: tyk-test
  labels:
    name: tyk-test

---

apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: tyk-test
  labels:
    app: httpbin
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 80
  selector:
    app: httpbin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: tyk-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
        - image: docker.io/kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          name: httpbin
          ports:
            - containerPort: 80

---

apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin
  namespace: tyk-test
spec:
  name: httpbin
  use_keyless: true
  protocol: http
  active: true
  proxy:
    target_url: http://httpbin.tyk-test.svc:8000
    listen_path: /bin
    strip_listen_path: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-pod
  namespace: tyk-test # Change the namespace if needed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
        labels:
          app: curl
    spec:
      containers:
      - name: curl-container
        image: curlimages/curl:7.85.0 # Using a minimal curl image
        command: ["/bin/sh", "-c"]
        args:
        - |
          for i in $(seq 1 10); do
            echo "Curl attempt $i";
            curl -s http://gateway-svc-tyk-oss-tyk-gateway.tyk-oss.svc:8080/httpbin/bin/get;
            sleep 100;
          done
