apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestore-policies
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: filestore-rwx
  nfs:
    path: /gkerwx  # This should be the path of your file share
    server: 10.106.177.210	  # The IP address of your Filestore instance
